config/routes.rb
Rails.application.routes.draw do
  get 'sessions/new'
  resources :enrollments
  get 'users/new'
  resources :parts
  resources :courses
  get 'static_pages/home'
  resources :subjects
  resources :instructors
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'static_pages#home'
  get '/instructors', to: 'instructors#index'
  get '/courses', to: 'courses#index'
  get '/subjects', to: 'instructors#index'
  get '/signup', to: 'users#new'
  # work around for refreshing invalid sign up
  get '/users', to: 'users#new'
  get '/login',   to: 'sessions#new'
  post '/login',   to: 'sessions#create'

  # work around for jquery and turbolink not working
  get '/logout',  to: 'sessions#destroy'
  get '/search' => 'static_pages#search', :as => 'search_page'
  post '/enroll', to: "enrollments#create"
  delete '/drop', to: "enrollments#destroy"
  resources :users
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  # static_page controller for home page
  # it will get query the enrolled courses for login user
  def home
    if current_user
      enrollment_ids = Enrollment.where(user_id: current_user.id).pluck(:course_id)
      @enrollments = Enrollment.where(user_id: current_user.id)
      @courses = Course.where(id: enrollment_ids)
    end
  end

  # search the course based on the search form
  def search
    # if the dropdown menu is not used, search all courses
    if params[:subject_id].blank?
      @courses = Course.where("lower(name) LIKE ?", "%#{params[:search_text]}%".downcase)
    # if dropdown menu is used, only search for selected subject
    else
      sub_class_ids = Part.where(subject_id: params[:subject_id].to_i).pluck(:course_id)
      @courses = Course.where(id: sub_class_ids).where("lower(name) LIKE ?", "%#{params[:search_text]}%".downcase)
    end
  end


end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/static_pages/home.html.erb
<div class="container">
  <div class="center jumbotron">
    <h1>Course Selection System</h1>

    <h2>
      This is the home page for Course Selection Part 2
    </h2>
    <% if logged_in? %>
      <div class="btn-group btn-group-lg">
        <%= link_to "Courses", courses_path, class: "btn btn-info" %>
        <%= link_to "Subjects", subjects_path, class: "btn btn-info" %>
        <%= link_to "Instructors", instructors_path, class: "btn btn-info" %>
      </div>
    <% else %>
      <%= link_to "Sign up", signup_path, class: "btn btn-info btn-lg" %>
    <% end %>
  </div>
</div>

<%# Show enrolled course if logged in %>
<% if logged_in? %>
  <%# If the user have not enrolled %>
  <% if @courses.count == 0%>
    <h1 class="adjust-context-center">You have not enrolled any courses!</h1>
  <% else %>
    <h1>Current Courses</h1>
    <div class="table-responsive">
      <table class="table table-hover">
          <thead class="thead-dark">
          <tr>
            <th>Code</th>
            <th>Name</th>
            <th>Subjects</th>
            <th>Description</th>
            <th colspan="3"></th>
          </tr>
        </thead>

        <tbody>
          
          <% @enrollments.each do |enrollment| %>
            <% course = Course.find(enrollment.course.id) %>
            <tr>
              <td><%= course.code %></td>
              <td><%= course.name %></td>
              <td><%= course.subjects_info %></td>
              <td><%= course.description %></td>
              <td><%= link_to 'Details', course, class: "btn btn-outline-info my-2 my-sm-0", type: "submit"%> </td>
              <td><%= link_to 'Drop', enrollment, method: :delete, class: "btn btn-outline-info my-2 my-sm-0", type: "submit", data: { confirm: 'Are you sure?' } %></td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  <% end %>
<% end %>

app/views/static_pages/search.html.erb
<% provide(:title, "Class Search") %>
<p id="notice"><%= notice %></p>

<h1>Courses</h1>

<div class="table-responsive">
  <table class="table table-hover">
      <thead class="thead-dark">
      <tr>
        <%# only show code name and subjects for a course %>
        <th>Id</th>
        <th>Code</th>
        <th>Name</th>
        <th>Subjects</th>
        <th>Description</th>
        <th colspan="3"></th>
      </tr>
    </thead>

    <tbody>
      <% @courses.each do |course| %>
        <tr>
          <td><%= course.id %></td>
          <td><%= course.code %></td>
          <td><%= course.name %></td>
          <td><%= course.subjects_info %></td>
          <td><%= course.description %></td>
          <td>
            <%= link_to 'Details', course, class: "btn btn-outline-info my-2 my-sm-0", type: "submit"%>
          </td>

          <td>
            <%# The enroll buttom %>
            <%= link_to 'Enroll', enroll_path(@enrollment, enrollment: {user_id: current_user.id, course_id: course.id}),
                                method: :post, data: { confirm: 'Are you sure?' }, class: "btn btn-outline-info my-2 my-sm-0",
                                type: "submit"%></td>
          </td>


        </tr>
      <% end %>
    </tbody>
  </table>
</div>