config/routes.rb
Rails.application.routes.draw do
  get 'sessions/new'
  resources :enrollments
  get 'users/new'
  resources :parts
  resources :courses
  get 'static_pages/home'
  resources :subjects
  resources :instructors
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'static_pages#home'
  get '/instructors', to: 'instructors#index'
  get '/courses', to: 'courses#index'
  get '/subjects', to: 'instructors#index'
  get '/signup', to: 'users#new'
  # work around for refreshing invalid sign up
  get '/users', to: 'users#new'
  get '/login',   to: 'sessions#new'
  post '/login',   to: 'sessions#create'

  # work around for jquery and turbolink not working
  get '/logout',  to: 'sessions#destroy'
  get '/search' => 'static_pages#search', :as => 'search_page'
  post '/enroll', to: "enrollments#create"
  delete '/drop', to: "enrollments#destroy"
  resources :users
end

app/models/instructor.rb
class Instructor < ApplicationRecord
end

app/controllers/instructors_controller.rb
class InstructorsController < ApplicationController
  before_action :set_instructor, only: [:show, :edit, :update, :destroy]

  # GET /instructors
  # GET /instructors.json
  def index
    @instructors = Instructor.all
  end

  # GET /instructors/1
  # GET /instructors/1.json
  def show
  end

  # GET /instructors/new
  def new
    @instructor = Instructor.new
  end

  # GET /instructors/1/edit
  def edit
  end

  # POST /instructors
  # POST /instructors.json
  def create
    @instructor = Instructor.new(instructor_params)

    respond_to do |format|
      if @instructor.save
        format.html { redirect_to @instructor, notice: 'Instructor was successfully created.' }
        format.json { render :show, status: :created, location: @instructor }
      else
        format.html { render :new }
        format.json { render json: @instructor.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /instructors/1
  # PATCH/PUT /instructors/1.json
  def update
    respond_to do |format|
      if @instructor.update(instructor_params)
        format.html { redirect_to @instructor, notice: 'Instructor was successfully updated.' }
        format.json { render :show, status: :ok, location: @instructor }
      else
        format.html { render :edit }
        format.json { render json: @instructor.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /instructors/1
  # DELETE /instructors/1.json
  def destroy
    @instructor.destroy
    respond_to do |format|
      format.html { redirect_to instructors_url, notice: 'Instructor was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_instructor
      @instructor = Instructor.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def instructor_params
      params.require(:instructor).permit(:instructor_id, :first, :middle, :last, :email, :comment)
    end
end

app/helpers/instructors_helper.rb
module InstructorsHelper
end

app/views/instructors/_form.html.erb
<%= form_with(model: instructor, local: true) do |form| %>
  <% if instructor.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(instructor.errors.count, "error") %> prohibited this instructor from being saved:</h2>

      <ul>
        <% instructor.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :instructor_id %>
    <%= form.text_field :instructor_id %>
  </div>

  <div class="field">
    <%= form.label :first %>
    <%= form.text_field :first %>
  </div>

  <div class="field">
    <%= form.label :middle %>
    <%= form.text_field :middle %>
  </div>

  <div class="field">
    <%= form.label :last %>
    <%= form.text_field :last %>
  </div>

  <div class="field">
    <%= form.label :email %>
    <%= form.text_field :email %>
  </div>

  <div class="field">
    <%= form.label :comment %>
    <%= form.text_field :comment %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/instructors/edit.html.erb
<h1>Editing Instructor</h1>

<%= render 'form', instructor: @instructor %>

<%= link_to 'Show', @instructor %> |
<%= link_to 'Back', instructors_path %>

app/views/instructors/index.html.erb
<% provide(:title, "Instructors") %>
<p id="notice"><%= notice %></p>

<h1>Instructors</h1>
<div class="table-responsive">
  <table class="table table-hover">
    <thead class="thead-dark">
      <tr>
        <th>Instructor</th>
        <th>First</th>
        <th>Last</th>
        <th>Email</th>
        <th>Comment</th>
        
        <th colspan="3"></th>
      </tr>
    </thead>

    <tbody>
      <% @instructors.each do |instructor| %>
        <tr>
          <td><%= instructor.instructor_id %></td>
          <td><%= instructor.first %></td>
          <td><%= instructor.last %></td>
          <td><%= instructor.email %></td>
          <td><%= instructor.comment %></td>
          <td><%= link_to 'Show', instructor %></td>
          <td><%= link_to 'Edit', edit_instructor_path(instructor) %></td>
          <td><%= link_to 'Destroy', instructor, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>
<br>

<%= link_to 'New Instructor', new_instructor_path %>

app/views/instructors/new.html.erb
<h1>New Instructor</h1>

<%= render 'form', instructor: @instructor %>

<%= link_to 'Back', instructors_path %>

app/views/instructors/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Instructor:</strong>
  <%= @instructor.instructor_id %>
</p>

<p>
  <strong>First:</strong>
  <%= @instructor.first %>
</p>

<p>
  <strong>Middle:</strong>
  <%= @instructor.middle %>
</p>

<p>
  <strong>Last:</strong>
  <%= @instructor.last %>
</p>

<p>
  <strong>Email:</strong>
  <%= @instructor.email %>
</p>

<p>
  <strong>Comment:</strong>
  <%= @instructor.comment %>
</p>

<%= link_to 'Edit', edit_instructor_path(@instructor) %> |
<%= link_to 'Back', instructors_path %>