config/routes.rb
Rails.application.routes.draw do
  get 'sessions/new'
  resources :enrollments
  get 'users/new'
  resources :parts
  resources :courses
  get 'static_pages/home'
  resources :subjects
  resources :instructors
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'static_pages#home'
  get '/instructors', to: 'instructors#index'
  get '/courses', to: 'courses#index'
  get '/subjects', to: 'instructors#index'
  get '/signup', to: 'users#new'
  # work around for refreshing invalid sign up
  get '/users', to: 'users#new'
  get '/login',   to: 'sessions#new'
  post '/login',   to: 'sessions#create'

  # work around for jquery and turbolink not working
  get '/logout',  to: 'sessions#destroy'
  get '/search' => 'static_pages#search', :as => 'search_page'
  post '/enroll', to: "enrollments#create"
  delete '/drop', to: "enrollments#destroy"
  resources :users
end

app/models/enrollment.rb
class Enrollment < ApplicationRecord
  belongs_to :user
  belongs_to :course

  validates :course_id, uniqueness: { scope: :user_id }
end

app/controllers/enrollments_controller.rb
class EnrollmentsController < ApplicationController
  before_action :set_enrollment, only: [:show, :edit, :update, :destroy]

  # GET /enrollments
  # GET /enrollments.json
  def index
    @enrollments = Enrollment.all
  end

  # GET /enrollments/1
  # GET /enrollments/1.json
  def show
  end

  # GET /enrollments/new
  def new
    @enrollment = Enrollment.new
  end

  # GET /enrollments/1/edit
  def edit
  end

  # POST /enrollments
  # POST /enrollments.json
  def create
    @enrollment = Enrollment.new(enrollment_params)

    respond_to do |format|
      if @enrollment.save
        format.html { redirect_to root_url, notice: 'You have successfully enrolled in this selected courses.' }
        format.json { render :show, status: :created, location: @enrollment }
      else
        format.html { redirect_to root_url, notice: 'You already enrolled this course before.' }
        format.json { render json: @enrollment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /enrollments/1
  # PATCH/PUT /enrollments/1.json
  def update
    respond_to do |format|
      if @enrollment.update(enrollment_params)
        format.html { redirect_to @enrollment, notice: 'Enrollment was successfully updated.' }
        format.json { render :show, status: :ok, location: @enrollment }
      else
        format.html { render :edit }
        format.json { render json: @enrollment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /enrollments/1
  # DELETE /enrollments/1.json
  def destroy
    @enrollment.destroy
    respond_to do |format|
      format.html { redirect_to root_url, notice: 'You have successfully dropped this course.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_enrollment
      @enrollment = Enrollment.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def enrollment_params
      params.require(:enrollment).permit(:user_id, :course_id)
    end
end

app/helpers/enrollments_helper.rb
module EnrollmentsHelper
end

app/views/enrollments/_form.html.erb
<%= form_with(model: enrollment, local: true) do |form| %>
  <% if enrollment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(enrollment.errors.count, "error") %> prohibited this enrollment from being saved:</h2>

      <ul>
        <% enrollment.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :user_id %>
    <%= form.text_field :user_id %>
  </div>

  <div class="field">
    <%= form.label :course_id %>
    <%= form.text_field :course_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/enrollments/edit.html.erb
<h1>Editing Enrollment</h1>

<%= render 'form', enrollment: @enrollment %>

<%= link_to 'Show', @enrollment %> |
<%= link_to 'Back', enrollments_path %>

app/views/enrollments/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Enrollments</h1>

<table>
  <thead>
    <tr>
      <th>User</th>
      <th>Course</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @enrollments.each do |enrollment| %>
      <tr>
        <td><%= enrollment.user_id %></td>
        <td><%= enrollment.course_id %></td>
        <td><%= link_to 'Show', enrollment %></td>
        <td><%= link_to 'Edit', edit_enrollment_path(enrollment) %></td>
        <td><%= link_to 'Destroy', enrollment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Enrollment', new_enrollment_path %>

app/views/enrollments/new.html.erb
<h1>New Enrollment</h1>

<%= render 'form', enrollment: @enrollment %>

<%= link_to 'Back', enrollments_path %>

app/views/enrollments/show.html.erb
<p id="notice"><%= notice %></p>

<div class="table-responsive">
  <table class="table table-hover">
      <thead class="thead-dark">
      <tr>
        <th>Student</th>
        <th>Course Code</th>
        <th>Course Name</th>
        <th colspan="3"></th>
      </tr>
      </thead>

      <tbody>
        <tr>
          <td><%= User.find(@enrollment.user_id).name %></td>
          <td><%= Course.find(@enrollment.course_id).code %></td>
          <td><%= Course.find(@enrollment.course_id).name %></td>
        <tr>
      </tbody>
  </table>
</div>

<%= link_to 'Back', enrollments_path %>