config/routes.rb
Rails.application.routes.draw do
  get 'sessions/new'
  resources :enrollments
  get 'users/new'
  resources :parts
  resources :courses
  get 'static_pages/home'
  resources :subjects
  resources :instructors
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'static_pages#home'
  get '/instructors', to: 'instructors#index'
  get '/courses', to: 'courses#index'
  get '/subjects', to: 'instructors#index'
  get '/signup', to: 'users#new'
  # work around for refreshing invalid sign up
  get '/users', to: 'users#new'
  get '/login',   to: 'sessions#new'
  post '/login',   to: 'sessions#create'

  # work around for jquery and turbolink not working
  get '/logout',  to: 'sessions#destroy'
  get '/search' => 'static_pages#search', :as => 'search_page'
  post '/enroll', to: "enrollments#create"
  delete '/drop', to: "enrollments#destroy"
  resources :users
end

app/models/subject.rb
class Subject < ApplicationRecord
  # add many to many relation to courses
  has_many :parts
  has_many :courses, through: :parts
end

app/controllers/subjects_controller.rb
class SubjectsController < ApplicationController
  before_action :set_subject, only: [:show, :edit, :update, :destroy]

  # GET /subjects
  # GET /subjects.json
  def index
    @subjects = Subject.all
  end

  # GET /subjects/1
  # GET /subjects/1.json
  def show
  end

  # GET /subjects/new
  def new
    @subject = Subject.new
  end

  # GET /subjects/1/edit
  def edit
  end

  # POST /subjects
  # POST /subjects.json
  def create
    @subject = Subject.new(subject_params)

    respond_to do |format|
      if @subject.save
        format.html { redirect_to @subject, notice: 'Subject was successfully created.' }
        format.json { render :show, status: :created, location: @subject }
      else
        format.html { render :new }
        format.json { render json: @subject.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /subjects/1
  # PATCH/PUT /subjects/1.json
  def update
    respond_to do |format|
      if @subject.update(subject_params)
        format.html { redirect_to @subject, notice: 'Subject was successfully updated.' }
        format.json { render :show, status: :ok, location: @subject }
      else
        format.html { render :edit }
        format.json { render json: @subject.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /subjects/1
  # DELETE /subjects/1.json
  def destroy
    @subject.destroy
    respond_to do |format|
      format.html { redirect_to subjects_url, notice: 'Subject was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_subject
      @subject = Subject.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def subject_params
      params.require(:subject).permit(:subject_id, :name, :abbreviation, :segments, :term, :comment)
    end
end

app/helpers/subjects_helper.rb
module SubjectsHelper
end

app/views/subjects/_form.html.erb
<%= form_with(model: subject, local: true) do |form| %>
  <% if subject.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(subject.errors.count, "error") %> prohibited this subject from being saved:</h2>

      <ul>
        <% subject.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :subject_id %>
    <%= form.text_field :subject_id %>
  </div>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :abbreviation %>
    <%= form.text_field :abbreviation %>
  </div>

  <div class="field">
    <%= form.label :segments %>
    <%= form.text_field :segments %>
  </div>

  <div class="field">
    <%= form.label :term %>
    <%= form.text_field :term %>
  </div>

  <div class="field">
    <%= form.label :comment %>
    <%= form.text_field :comment %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/subjects/edit.html.erb
<h1>Editing Subject</h1>

<%= render 'form', subject: @subject %>

<%= link_to 'Show', @subject %> |
<%= link_to 'Back', subjects_path %>

app/views/subjects/index.html.erb
<% provide(:title, "Subjects") %>
<p id="notice"><%= notice %></p>

<h1>Subjects</h1>

<div class="row justify-content-center">
  <div class="col-md-6 col-md-offset-3">
    <%= form_with(model: @subject, local: true) do |f| %>
      <%= f.select(:subject_id, Subject.all.collect {|s| [s.name, s.id, s.subject_id] },  {prompt: "Select"}, {class: 'form-control'}) %>
    <% end %>
  </div>
</div>


<div class="table-responsive">
  <table class="table table-hover">
      <thead class="thead-dark">
      <tr>
        <th>Subject</th>
        <th>Name</th>
        <th>Segments</th>
        <th colspan="3"></th>
      </tr>
    </thead>

    <tbody>
      <% @subjects.each do |subject| %>
        <tr>
          <td><%= subject.subject_id %></td>
          <td><%= subject.name %></td>
          <td><%= subject.segments %></td>
          <td><%= link_to 'Show', subject %></td>
          <td><%= link_to 'Edit', edit_subject_path(subject) %></td>
          <td><%= link_to 'Destroy', subject, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>
<br>

<%= link_to 'New Subject', new_subject_path %>

app/views/subjects/new.html.erb
<h1>New Subject</h1>

<%= render 'form', subject: @subject %>

<%= link_to 'Back', subjects_path %>

app/views/subjects/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Subject:</strong>
  <%= @subject.subject_id %>
</p>

<p>
  <strong>Name:</strong>
  <%= @subject.name %>
</p>

<p>
  <strong>Abbreviation:</strong>
  <%= @subject.abbreviation %>
</p>

<p>
  <strong>Segments:</strong>
  <%= @subject.segments %>
</p>

<p>
  <strong>Term:</strong>
  <%= @subject.term %>
</p>

<p>
  <strong>Comment:</strong>
  <%= @subject.comment %>
</p>

<%= link_to 'Edit', edit_subject_path(@subject) %> |
<%= link_to 'Back', subjects_path %>